'use client';

import { useEffect, useState } from 'react';
import { AnimatePresence, motion, useReducedMotion } from 'motion/react';
import { toDataURL } from 'qrcode';
import {
  QrCode,
  Plus,
  Copy,
  Check,
  ArrowsOut,
  ArrowsClockwise,
  X,
  WarningOctagon,
  UsersThree,
} from '@phosphor-icons/react';
import { supabase } from '@/lib/supabase';
import { useLanguage } from '@/lib/i18n/LanguageContext';
import { formatInviteCode, joinUrl } from '@/lib/invite';

// ---------------------------------------------------------------------------
// Coach side of team invites: create a team, show its QR code, copy the link,
// open the QR full-screen to show a whole locker room at once, close sign-ups,
// or rotate the code. The code itself is generated by the database; this
// component only ever sends the team name (08_team_invites.sql).
// ---------------------------------------------------------------------------

type Team = {
  id: string;
  name: string;
  invite_code: string;
  invite_active: boolean;
};

const QR_OPTIONS = { margin: 1, errorCorrectionLevel: 'M' as const, color: { dark: '#07080A', light: '#FFFFFF' } };

export default function TeamInvitePanel() {
  const { t } = useLanguage();
  const inv = t.invite;
  const reduce = useReducedMotion();

  const [coachId, setCoachId] = useState<string | null>(null);
  const [teams, setTeams] = useState<Team[] | null>(null);
  const [counts, setCounts] = useState<Record<string, number>>({});
  const [qr, setQr] = useState<Record<string, string>>({});
  const [origin, setOrigin] = useState('');

  const [showCreate, setShowCreate] = useState(false);
  const [newName, setNewName] = useState('');
  const [creating, setCreating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [confirmRegen, setConfirmRegen] = useState<string | null>(null);
  const [busyId, setBusyId] = useState<string | null>(null);
  const [fullscreen, setFullscreen] = useState<{ team: Team; qr: string } | null>(null);

  // Load teams + how many athletes joined each.
  useEffect(() => {
    let cancelled = false;
    setOrigin(window.location.origin);
    (async () => {
      const { data: session } = await supabase.auth.getSession();
      const uid = session.session?.user?.id;
      if (!uid) return;
      const [{ data: teamRows }, { data: memberRows }] = await Promise.all([
        supabase.from('teams').select('id, name, invite_code, invite_active').eq('coach_id', uid).order('created_at'),
        supabase.from('team_members').select('team_id').eq('coach_id', uid),
      ]);
      if (cancelled) return;
      const list = (teamRows as Team[] | null) ?? [];
      const c: Record<string, number> = {};
      for (const m of (memberRows as { team_id: string | null }[] | null) ?? []) {
        if (m.team_id) c[m.team_id] = (c[m.team_id] ?? 0) + 1;
      }
      setCoachId(uid);
      setCounts(c);
      setTeams(list);
      setShowCreate(list.length === 0);
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  // (Re)draw QR codes whenever a code changes.
  useEffect(() => {
    if (!teams || !origin) return;
    let cancelled = false;
    Promise.all(
      teams.map(async (team) => [team.invite_code, await toDataURL(joinUrl(origin, team.invite_code), { ...QR_OPTIONS, width: 240 })] as const)
    ).then((pairs) => {
      if (!cancelled) setQr(Object.fromEntries(pairs));
    });
    return () => {
      cancelled = true;
    };
  }, [teams, origin]);

  // Esc closes the full-screen QR.
  useEffect(() => {
    if (!fullscreen) return;
    const onKey = (e: KeyboardEvent) => e.key === 'Escape' && setFullscreen(null);
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [fullscreen]);

  async function createTeam(e: React.FormEvent) {
    e.preventDefault();
    const name = newName.trim();
    if (!name || !coachId) return;
    setCreating(true);
    setError(null);
    const { data, error: err } = await supabase
      .from('teams')
      .insert({ coach_id: coachId, name })
      .select('id, name, invite_code, invite_active')
      .single();
    setCreating(false);
    if (err || !data) {
      setError(inv.errCreate);
      return;
    }
    setTeams((cur) => [...(cur ?? []), data as Team]);
    setNewName('');
    setShowCreate(false);
  }

  async function toggleInvite(team: Team) {
    setBusyId(team.id);
    setError(null);
    const { error: err } = await supabase.from('teams').update({ invite_active: !team.invite_active }).eq('id', team.id);
    setBusyId(null);
    if (err) {
      setError(inv.errAction);
      return;
    }
    setTeams((cur) => cur?.map((x) => (x.id === team.id ? { ...x, invite_active: !x.invite_active } : x)) ?? cur);
  }

  async function regenerate(team: Team) {
    setBusyId(team.id);
    setError(null);
    const { data, error: err } = await supabase.rpc('regenerate_team_invite', { p_team: team.id });
    setBusyId(null);
    setConfirmRegen(null);
    if (err || typeof data !== 'string') {
      setError(inv.errAction);
      return;
    }
    setTeams((cur) => cur?.map((x) => (x.id === team.id ? { ...x, invite_code: data } : x)) ?? cur);
  }

  async function copyLink(team: Team) {
    try {
      await navigator.clipboard.writeText(joinUrl(origin, team.invite_code));
      setCopiedId(team.id);
      setTimeout(() => setCopiedId((cur) => (cur === team.id ? null : cur)), 2000);
    } catch {
      setError(inv.errAction);
    }
  }

  async function openFullscreen(team: Team) {
    const big = await toDataURL(joinUrl(origin, team.invite_code), { ...QR_OPTIONS, width: 720 });
    setFullscreen({ team, qr: big });
  }

  if (teams === null) return null;

  const card = 'rounded-3xl bg-white/[0.03] p-5 ring-1 ring-inset ring-white/[0.08] backdrop-blur-2xl';
  const ghostBtn =
    'inline-flex items-center gap-1.5 rounded-full bg-white/[0.04] px-3 py-1.5 text-xs font-medium text-zinc-200 ring-1 ring-inset ring-white/10 transition-colors hover:bg-white/[0.08] disabled:opacity-50';

  return (
    <section className="mb-6 space-y-3">
      <div className="flex flex-wrap items-end justify-between gap-2">
        <div>
          <h2 className="flex items-center gap-2 text-base font-semibold tracking-[-0.01em] text-zinc-50">
            <QrCode size={18} weight="fill" className="text-[#CCFF00]" />
            {inv.panelTitle}
          </h2>
          <p className="mt-1 max-w-[56ch] text-xs leading-relaxed text-zinc-400">{inv.panelHint}</p>
        </div>
        {teams.length > 0 && !showCreate && (
          <button type="button" onClick={() => setShowCreate(true)} className={ghostBtn}>
            <Plus size={13} weight="bold" />
            {inv.addTeam}
          </button>
        )}
      </div>

      {error && (
        <div className="flex gap-3 rounded-2xl bg-[#FF4D5E]/[0.08] p-3 text-sm text-zinc-200 ring-1 ring-inset ring-[#FF4D5E]/30">
          <WarningOctagon size={16} weight="fill" className="mt-0.5 shrink-0 text-[#FF4D5E]" />
          <span>{error}</span>
        </div>
      )}

      {showCreate && (
        <form onSubmit={createTeam} className={`${card} flex flex-col gap-3 sm:flex-row sm:items-end`}>
          <label className="flex-1">
            <span className="text-xs text-zinc-400">{inv.teamName}</span>
            <input
              type="text"
              value={newName}
              onChange={(e) => setNewName(e.target.value)}
              maxLength={60}
              placeholder={inv.teamNamePlaceholder}
              className="mt-1.5 w-full rounded-xl bg-white/[0.05] px-3.5 py-2.5 text-sm text-zinc-50 placeholder-zinc-500 ring-1 ring-inset ring-white/10 focus:outline-none focus:ring-[#CCFF00]/50"
            />
          </label>
          <div className="flex gap-2">
            {teams.length > 0 && (
              <button type="button" onClick={() => setShowCreate(false)} className="rounded-xl px-3 py-2.5 text-sm text-zinc-400 hover:text-zinc-200">
                {inv.cancel}
              </button>
            )}
            <button
              type="submit"
              disabled={creating || !newName.trim()}
              className="rounded-xl bg-[#CCFF00] px-4 py-2.5 text-sm font-semibold text-zinc-950 disabled:opacity-50"
            >
              {creating ? inv.creating : inv.createTeam}
            </button>
          </div>
        </form>
      )}

      {teams.map((team) => {
        const busy = busyId === team.id;
        return (
          <div key={team.id} className={`${card} flex flex-col gap-5 sm:flex-row`}>
            <div className="flex shrink-0 flex-col items-center gap-2">
              <div
                className={`rounded-2xl bg-white p-2 transition-opacity ${team.invite_active ? '' : 'opacity-25'}`}
                style={{ width: 176, height: 176 }}
              >
                {qr[team.invite_code] && (
                  // eslint-disable-next-line @next/next/no-img-element
                  <img src={qr[team.invite_code]} alt={`QR ${team.name}`} width={160} height={160} />
                )}
              </div>
              <span className="text-[11px] text-zinc-500">{inv.scanHint}</span>
            </div>

            <div className="min-w-0 flex-1">
              <p className="text-lg font-semibold text-zinc-50">{team.name}</p>
              <p className="mt-0.5 inline-flex items-center gap-1.5 text-xs text-zinc-400">
                <UsersThree size={13} weight="fill" />
                {inv.members(counts[team.id] ?? 0)}
              </p>

              <p className="mt-4 text-xs text-zinc-500">{inv.codeLabel}</p>
              <p className="font-mono text-2xl tracking-[0.12em] text-zinc-50">{formatInviteCode(team.invite_code)}</p>

              <div className="mt-4 flex flex-wrap gap-2">
                <button type="button" onClick={() => copyLink(team)} className={ghostBtn}>
                  {copiedId === team.id ? <Check size={13} weight="bold" className="text-[#CCFF00]" /> : <Copy size={13} />}
                  {copiedId === team.id ? inv.copied : inv.copyLink}
                </button>
                <button type="button" onClick={() => openFullscreen(team)} disabled={!team.invite_active} className={ghostBtn}>
                  <ArrowsOut size={13} />
                  {inv.fullscreen}
                </button>
                <button type="button" onClick={() => setConfirmRegen(team.id)} disabled={busy} className={ghostBtn}>
                  <ArrowsClockwise size={13} />
                  {inv.newCode}
                </button>
              </div>

              {confirmRegen === team.id && (
                <div className="mt-3 rounded-2xl bg-white/[0.04] p-3 text-xs leading-relaxed text-zinc-300 ring-1 ring-inset ring-white/10">
                  {inv.newCodeConfirm}
                  <div className="mt-2 flex gap-2">
                    <button
                      type="button"
                      onClick={() => regenerate(team)}
                      disabled={busy}
                      className="rounded-full bg-[#CCFF00] px-3 py-1.5 font-semibold text-zinc-950 disabled:opacity-50"
                    >
                      {inv.confirm}
                    </button>
                    <button type="button" onClick={() => setConfirmRegen(null)} className="px-2 text-zinc-400 hover:text-zinc-200">
                      {inv.cancel}
                    </button>
                  </div>
                </div>
              )}

              <div className="mt-4 flex items-center justify-between gap-3 border-t border-white/[0.06] pt-3">
                <div>
                  <p className="text-sm text-zinc-200">{inv.accepting}</p>
                  <p className="text-xs" style={{ color: team.invite_active ? '#CCFF00' : '#A1A1AA' }}>
                    {team.invite_active ? inv.acceptingOn : inv.acceptingOff}
                  </p>
                </div>
                <button
                  type="button"
                  role="switch"
                  aria-checked={team.invite_active}
                  aria-label={`${inv.accepting}: ${team.name}`}
                  disabled={busy}
                  onClick={() => toggleInvite(team)}
                  className={`relative h-7 w-12 shrink-0 rounded-full transition-colors duration-200 disabled:opacity-60 ${
                    team.invite_active ? 'bg-[#CCFF00]' : 'bg-white/[0.12]'
                  }`}
                >
                  <span
                    className={`absolute left-0.5 top-0.5 h-6 w-6 rounded-full shadow transition-transform duration-200 ${
                      team.invite_active ? 'translate-x-5 bg-zinc-950' : 'translate-x-0 bg-zinc-300'
                    }`}
                  />
                </button>
              </div>
            </div>
          </div>
        );
      })}

      <AnimatePresence>
        {fullscreen && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: reduce ? 0 : 0.2 }}
            className="fixed inset-0 z-50 flex flex-col items-center justify-center gap-5 bg-[#07080A]/95 p-6 backdrop-blur-xl"
            onClick={() => setFullscreen(null)}
            role="dialog"
            aria-modal="true"
            aria-label={fullscreen.team.name}
          >
            <button
              type="button"
              onClick={() => setFullscreen(null)}
              aria-label={inv.close}
              className="absolute right-4 top-4 flex h-10 w-10 items-center justify-center rounded-full bg-white/10 text-zinc-200"
            >
              <X size={18} weight="bold" />
            </button>
            <p className="text-center text-2xl font-semibold text-zinc-50 md:text-3xl">{fullscreen.team.name}</p>
            <div className="rounded-3xl bg-white p-4" onClick={(e) => e.stopPropagation()}>
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={fullscreen.qr}
                alt={`QR ${fullscreen.team.name}`}
                className="h-auto w-[min(72vw,58vh,440px)]"
              />
            </div>
            <p className="font-mono text-3xl tracking-[0.16em] text-zinc-50 md:text-4xl">
              {formatInviteCode(fullscreen.team.invite_code)}
            </p>
            <p className="text-sm text-zinc-400">{inv.scanHint}</p>
          </motion.div>
        )}
      </AnimatePresence>
    </section>
  );
}
